using System.Globalization;
using CodexProfileOverlay.Core.Models;

namespace CodexProfileOverlay.Core.Services;

public static class LocalizationCatalog
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["OpenCodex"] = "Open Codex",
        ["ShowSwitcher"] = "Show switcher",
        ["HideSwitcher"] = "Hide switcher",
        ["Profiles"] = "Profiles",
        ["Settings"] = "Settings",
        ["StartWithWindows"] = "Start with Windows",
        ["Exit"] = "Exit",
        ["Active"] = "Active",
        ["AddProfile"] = "Add profile",
        ["ManageProfiles"] = "Manage profiles",
        ["Rename"] = "Rename",
        ["OpenFolder"] = "Open folder",
        ["Remove"] = "Remove",
        ["SwitchingToProfile"] = "Switching to {0}...",
        ["SwitchedToAccount"] = "Switched to account: {0}",
        ["PreviousAuthorizationRestored"] = "Previous authorization was restored",
        ["General"] = "General",
        ["Appearance"] = "Appearance",
        ["Hotkeys"] = "Hotkeys",
        ["Language"] = "Language",
        ["ThemeLight"] = "Light theme",
        ["ThemeDark"] = "Dark theme",
        ["SwitchToLightTheme"] = "Switch to light theme",
        ["SwitchToDarkTheme"] = "Switch to dark theme",
        ["Advanced"] = "Advanced",
        ["Close"] = "Close",
        ["Refresh"] = "Refresh",
        ["Done"] = "Done",
        ["NoReadyProfiles"] = "No ready profiles",
        ["ToggleSwitcher"] = "Toggle switcher",
        ["RestoreDefaults"] = "Restore defaults",
        ["ResetHotkeys"] = "Reset hotkeys",
        ["PressShortcut"] = "Press a shortcut...",
        ["None"] = "None",
        ["Applied"] = "Applied",
        ["DisplayMode"] = "Display mode",
        ["PositionPreset"] = "Position preset",
        ["OffsetX"] = "X offset",
        ["OffsetY"] = "Y offset",
        ["UiScale"] = "UI scale",
        ["Animations"] = "Animations",
        ["ShowAutomatically"] = "Show automatically when Codex opens",
        ["LaunchOnStart"] = "Launch Codex when overlay starts",
        ["LaunchAfterSwitch"] = "Launch Codex after switching",
        ["GracefulTimeout"] = "Graceful close timeout",
        ["ForceCloseFallback"] = "Force-close fallback",
        ["ConfirmForceClose"] = "Confirm account switch",
        ["ConfirmSwitchTitle"] = "Switch account?",
        ["ConfirmSwitchPrompt"] = "Codex will close and switch to profile \"{0}\". The account will only be changed after you confirm.",
        ["ConfirmSwitchPrimary"] = "Switch account",
        ["CodexCouldNotLaunch"] = "Codex could not be opened automatically.",
        ["SystemDefault"] = "System default",
        ["English"] = "English",
        ["Russian"] = "Русский",
        ["DirectoryName"] = "Directory name",
        ["OpenProfilesFolder"] = "Open profiles folder",
        ["OpenRemovedProfilesFolder"] = "Open removed profiles folder",
        ["OpenApplicationData"] = "Open app data",
        ["OpenBackups"] = "Open backups",
        ["BackupStorageSummary"] = "Current backup storage: {0}\nRetained completed backups: {1}\nRetention limit: {2} backups / {3}, 7 days",
        ["CleanLegacyBackups"] = "Clean legacy backups",
        ["CleanCompletedBackups"] = "Clean all completed backups",
        ["LegacyBackupCleanupPrompt"] = "Legacy backup directories: {0}\nTotal size: {1}\nOldest: {2}\nNewest: {3}\nEstimated space to reclaim: {4}\n\nThe two newest legacy backups will be retained.",
        ["CompletedBackupCleanupPrompt"] = "Delete all completed rollback backups? Active transactions will be preserved.",
        ["NoLegacyBackups"] = "No legacy backups were found.",
        ["BackupCleanupCompleted"] = "Backup cleanup completed.",
        ["Clean"] = "Clean",
        ["OpenLogs"] = "Open logs",
        ["ResetPosition"] = "Reset position",
        ["ResetSettings"] = "Reset settings",
        ["ExitApplication"] = "Exit application",
        ["CouldNotRefreshProfiles"] = "Could not refresh profiles. Check the profiles folder.",
        ["HotkeysCouldNotRegister"] = "One or more hotkeys could not be registered.",
        ["ForceClosePrompt"] = "Codex will be asked to close gracefully. If it is still running after the timeout, allow force closing Codex to complete the switch?",
        ["CouldNotSwitch"] = "Could not switch account.",
        ["AddProfileTitle"] = "Add profile",
        ["ProfileDirectoryName"] = "Profile directory name",
        ["StartingLogin"] = "Starting Codex login for {0}...",
        ["AuthNotCreated"] = "Login finished, but auth.json was not created.",
        ["ProfileAdded"] = "Profile added successfully",
        ["SwitchNewProfile"] = "Switch to the newly added profile now?",
        ["CouldNotAddProfile"] = "Could not add profile.",
        ["RenameDisplayName"] = "Rename display name",
        ["DisplayName"] = "Display name",
        ["ProfileRenamed"] = "Profile renamed",
        ["ActiveProfileCannotRename"] = "The active profile folder cannot be renamed.",
        ["ActiveProfileCannotRemove"] = "The active profile cannot be removed.",
        ["RemoveProfilePrompt"] = "This moves the local saved login to the removed-profiles folder. It does not delete your ChatGPT account.",
        ["ProfileRemoved"] = "Profile removed from switcher",
        ["StartupCouldNotUpdate"] = "Start with Windows could not be updated.",
        ["Add"] = "Add",
        ["Save"] = "Save",
        ["Cancel"] = "Cancel",
        ["DisplayModeHelp"] = "Auto chooses compact mode for narrow Codex windows.",
        ["PositionPresetHelp"] = "After menu places the switcher just to the right of the native menu row.",
        ["OffsetXHelp"] = "Drag horizontally or type a value.",
        ["OffsetYHelp"] = "Drag vertically or type a value.",
        ["UiScaleHelp"] = "Scale the overlay without changing Codex.",
        ["AnimationsHelp"] = "Enables short hover and notification transitions.",
        ["StartWithWindowsHelp"] = "Registers the published executable for Windows sign-in.",
        ["ShowAutomaticallyHelp"] = "Controls automatic display when a Codex window is available.",
        ["LaunchOnStartHelp"] = "Starts Codex when this tray app starts.",
        ["LaunchAfterSwitchHelp"] = "Reopens Codex after a completed account switch.",
        ["LanguageHelp"] = "System default follows Windows display language.",
        ["GracefulTimeoutHelp"] = "Seconds to wait before optional force-close fallback.",
        ["ForceCloseFallbackHelp"] = "Allows switching to complete if Codex does not close gracefully.",
        ["ConfirmForceCloseHelp"] = "Asks before Codex is closed and the active account is changed.",
        ["HotkeyHelp"] = "Click the field, then press the shortcut. Escape cancels; Backspace clears.",
        ["UseModifier"] = "Use at least one modifier.",
        ["InvalidNumber"] = "Invalid number.",
        ["CouldNotSaveSettings"] = "Could not save settings.",
        ["ExportSettings"] = "Export settings",
        ["ImportSettings"] = "Import settings",
        ["ProfileHotkey"] = "Profile {0}: {1}",
        ["Switching"] = "Switching...",
        ["AfterMenu"] = "After menu",
        ["TopCenter"] = "Top center",
        ["TopRight"] = "Top right",
        ["TopLeft"] = "Top left",
        ["Custom"] = "Custom",
        ["Auto"] = "Auto",
        ["Compact"] = "Compact",
        ["Expanded"] = "Expanded",

        // Status and limits localization
        ["StatusAndLimits"] = "Status and limits",
        ["ShowAutomaticLimitIndicators"] = "Automatic limit indicators",
        ["ShowAutomaticLimitIndicatorsHelp"] = "Checks available Codex limits and displays a small status emoji beside each profile.",
        ["ShowIndicatorsInOverlay"] = "Show indicators in overlay",
        ["ShowIndicatorsInOverlayHelp"] = "Displays limit indicators in the overlay profile buttons and compact profile list.",
        ["ShowManualEmoji"] = "Show manual profile emoji in overlay",
        ["ShowManualEmojiHelp"] = "Disabled by default. An automatic indicator takes priority when both are available.",
        ["GreenThreshold"] = "Green threshold (%)",
        ["GreenThresholdHelp"] = "Green is shown at this percentage or higher.",
        ["YellowThreshold"] = "Yellow threshold (%)",
        ["YellowThresholdHelp"] = "Yellow starts at this percentage; lower values are red.",
        ["StaleDataThreshold"] = "Stale data threshold (minutes)",
        ["StaleDataThresholdHelp"] = "Minutes of inactivity before usage data is considered stale.",
        ["LowWarningThreshold"] = "Low warning threshold (%)",
        ["LowWarningThresholdHelp"] = "Percentage threshold for low limit warnings.",
        ["ActiveProfileRefreshInterval"] = "Active profile refresh interval (minutes)",
        ["ActiveProfileRefreshIntervalHelp"] = "Minutes between automatic refreshes for the active profile.",
        ["InactiveProfileRefreshInterval"] = "Inactive profile refresh interval (minutes)",
        ["InactiveProfileRefreshIntervalHelp"] = "Minutes between automatic refreshes for inactive profiles.",
        ["WarnNearlyExhausted"] = "Warn when a profile is nearly exhausted",
        ["WarnNearlyExhaustedHelp"] = "Shows one deduplicated local notification when a supported source reports low capacity.",
        ["AutomaticLimitsUnavailable"] = "Automatic limits unavailable",
        ["AutomaticLimitsUnavailableHelp"] = "Automatic checks require a Codex CLI with app-server rate-limit support. Use the support test before enabling background checks.",
        ["IndicatorLegend"] = "Indicator legend",
        ["AutomaticIndicatorExplanation"] = "The indicator uses the most restrictive available window. Values may be delayed; no emoji means reliable current data is unavailable. ⭐ is a recommendation, not a guarantee. Disabling automatic indicators removes every automatic emoji.",
        ["ManualProfileStatus"] = "Manual profile status",
        ["ManualEmoji"] = "Emoji",
        ["ManualEmojiHelp"] = "Optional custom emoji. Stored as local profile metadata.",
        ["ManualLabel"] = "Short status text",
        ["ManualLabelHelp"] = "Optional, up to 24 characters. It is only shown in Settings.",
        ["ManualNote"] = "Note",
        ["ManualNoteHelp"] = "Optional, up to 120 characters. It is never written to profile credentials.",
        ["ManualResetAt"] = "Reset date and time",
        ["ManualResetAtHelp"] = "Optional local date and time. It is stored internally as UTC.",
        ["CheckThisProfileAutomatically"] = "Check this profile automatically",
        ["CheckThisProfileAutomaticallyHelp"] = "Used only when a supported usage provider is available.",
        ["InvalidDateTime"] = "Invalid date or time.",
        ["RefreshNow"] = "Refresh now",
        ["TestProviderSupport"] = "Test provider support",
        ["LastSuccessfulRefresh"] = "Last successful refresh",
        ["LastSafeError"] = "Last safe error",
        ["ClearManualStatus"] = "Clear manual status",
        ["ClearCachedUsage"] = "Clear cached automatic data",
        ["ProviderAvailable"] = "Automatic usage provider available",
        ["NoReliableUsageData"] = "No reliable current usage data. Unknown values are not displayed as zero.",
        ["ResetsAt"] = "resets at",
        ["LastUpdated"] = "Last updated",
        ["UsageDataStale"] = "Usage data is stale",
        ["UsageSource"] = "Source",
        ["CodexCliVersion"] = "Codex CLI version",
        ["LastRefreshAttempt"] = "Last refresh attempt",
        ["RefreshError"] = "Refresh error",
        ["UsageWindow"] = "Limit",

        // Legend
        ["RecommendedProfile"] = "Recommended profile",
        ["RecommendedProfileHelp"] = "It currently has the highest available capacity among checked profiles.",
        ["HighCapacity"] = "High capacity",
        ["HighCapacityHelp"] = "The profile has plenty of remaining usage.",
        ["MediumCapacity"] = "Medium capacity",
        ["MediumCapacityHelp"] = "A noticeable part of the limit has already been used.",
        ["LowCapacity"] = "Low or exhausted",
        ["LowCapacityHelp"] = "Choose another profile or wait for the limit to reset.",

        // Manual status presets
        ["PresetReady"] = "Ready",
        ["PresetPartlyUsed"] = "Partly used",
        ["PresetLow"] = "Low",
        ["PresetExhausted"] = "Exhausted",
        ["PresetResetsSoon"] = "Resets soon",
        ["PresetInactive"] = "Inactive",
        ["PresetUnknown"] = "Unknown",
    };

    private static readonly IReadOnlyDictionary<string, string> Russian = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["OpenCodex"] = "Открыть Codex",
        ["ShowSwitcher"] = "Показать переключатель",
        ["HideSwitcher"] = "Скрыть переключатель",
        ["Profiles"] = "Профили",
        ["Settings"] = "Настройки",
        ["StartWithWindows"] = "Запускать вместе с Windows",
        ["Exit"] = "Выйти",
        ["Active"] = "Активен",
        ["AddProfile"] = "Добавить профиль",
        ["ManageProfiles"] = "Управление профилями",
        ["Rename"] = "Переименовать",
        ["OpenFolder"] = "Открыть папку",
        ["Remove"] = "Удалить",
        ["SwitchingToProfile"] = "Переключение на {0}...",
        ["SwitchedToAccount"] = "Аккаунт переключён: {0}",
        ["PreviousAuthorizationRestored"] = "Предыдущая авторизация восстановлена",
        ["General"] = "Общие",
        ["Appearance"] = "Внешний вид",
        ["Hotkeys"] = "Горячие клавиши",
        ["Language"] = "Язык",
        ["ThemeLight"] = "Светлая тема",
        ["ThemeDark"] = "Темная тема",
        ["SwitchToLightTheme"] = "Включить светлую тему",
        ["SwitchToDarkTheme"] = "Включить темную тему",
        ["Advanced"] = "Дополнительно",
        ["Close"] = "Закрыть",
        ["Refresh"] = "Обновить",
        ["Done"] = "Готово",
        ["NoReadyProfiles"] = "Нет готовых профилей",
        ["ToggleSwitcher"] = "Переключить панель",
        ["RestoreDefaults"] = "Восстановить по умолчанию",
        ["ResetHotkeys"] = "Сбросить хоткеи",
        ["PressShortcut"] = "Нажмите сочетание...",
        ["None"] = "Нет",
        ["Applied"] = "Применено",
        ["DisplayMode"] = "Режим отображения",
        ["PositionPreset"] = "Положение",
        ["OffsetX"] = "Смещение X",
        ["OffsetY"] = "Смещение Y",
        ["UiScale"] = "Масштаб UI",
        ["Animations"] = "Анимации",
        ["ShowAutomatically"] = "Показывать автоматически при открытии Codex",
        ["LaunchOnStart"] = "Запускать Codex при старте панели",
        ["LaunchAfterSwitch"] = "Запускать Codex после переключения",
        ["GracefulTimeout"] = "Таймаут мягкого закрытия",
        ["ForceCloseFallback"] = "Принудительное закрытие при сбое",
        ["ConfirmForceClose"] = "Подтверждать смену аккаунта",
        ["ConfirmSwitchTitle"] = "Переключить аккаунт?",
        ["ConfirmSwitchPrompt"] = "Codex будет закрыт и переключится на профиль \"{0}\". Аккаунт сменится только после подтверждения.",
        ["ConfirmSwitchPrimary"] = "Переключить",
        ["CodexCouldNotLaunch"] = "Не удалось автоматически открыть Codex.",
        ["SystemDefault"] = "Как в системе",
        ["English"] = "English",
        ["Russian"] = "Русский",
        ["DirectoryName"] = "Имя папки",
        ["OpenProfilesFolder"] = "Открыть папку профилей",
        ["OpenRemovedProfilesFolder"] = "Открыть удалённые профили",
        ["OpenApplicationData"] = "Открыть данные приложения",
        ["OpenBackups"] = "Открыть резервные копии",
        ["BackupStorageSummary"] = "Текущий размер резервных копий: {0}\nСохранено завершённых копий: {1}\nЛимит хранения: {2} копий / {3}, 7 дней",
        ["CleanLegacyBackups"] = "Очистить старые резервные копии",
        ["CleanCompletedBackups"] = "Очистить все завершённые копии",
        ["LegacyBackupCleanupPrompt"] = "Старых каталогов резервных копий: {0}\nОбщий размер: {1}\nСамая старая: {2}\nСамая новая: {3}\nМожно освободить примерно: {4}\n\nДве самые новые старые копии будут сохранены.",
        ["CompletedBackupCleanupPrompt"] = "Удалить все завершённые резервные копии отката? Активные транзакции будут сохранены.",
        ["NoLegacyBackups"] = "Старые резервные копии не найдены.",
        ["BackupCleanupCompleted"] = "Очистка резервных копий завершена.",
        ["Clean"] = "Очистить",
        ["OpenLogs"] = "Открыть логи",
        ["ResetPosition"] = "Сбросить положение",
        ["ResetSettings"] = "Сбросить настройки",
        ["ExitApplication"] = "Выйти из приложения",
        ["CouldNotRefreshProfiles"] = "Не удалось обновить профили. Проверьте папку профилей.",
        ["HotkeysCouldNotRegister"] = "Не удалось зарегистрировать одну или несколько горячих клавиш.",
        ["ForceClosePrompt"] = "Codex будет закрыт штатно. Если он продолжит работать после таймаута, разрешить принудительное закрытие для завершения переключения?",
        ["CouldNotSwitch"] = "Не удалось переключить аккаунт.",
        ["AddProfileTitle"] = "Добавить профиль",
        ["ProfileDirectoryName"] = "Имя папки профиля",
        ["StartingLogin"] = "Запуск входа Codex для {0}...",
        ["AuthNotCreated"] = "Вход завершён, но auth.json не был создан.",
        ["ProfileAdded"] = "Профиль успешно добавлен",
        ["SwitchNewProfile"] = "Переключиться на новый профиль сейчас?",
        ["CouldNotAddProfile"] = "Не удалось добавить профиль.",
        ["RenameDisplayName"] = "Переименовать отображаемое имя",
        ["DisplayName"] = "Отображаемое имя",
        ["ProfileRenamed"] = "Профиль переименован",
        ["ActiveProfileCannotRename"] = "Папку активного профиля нельзя переименовать.",
        ["ActiveProfileCannotRemove"] = "Активный профиль нельзя удалить.",
        ["RemoveProfilePrompt"] = "Локальный сохранённый вход будет перемещён в папку removed-profiles. Это не удаляет ваш аккаунт ChatGPT.",
        ["ProfileRemoved"] = "Профиль удалён из переключателя",
        ["StartupCouldNotUpdate"] = "Не удалось обновить запуск вместе с Windows.",
        ["Add"] = "Добавить",
        ["Save"] = "Сохранить",
        ["Cancel"] = "Отмена",
        ["DisplayModeHelp"] = "Авто включает компактный режим для узких окон Codex.",
        ["PositionPresetHelp"] = "После меню размещает переключатель справа от встроенной строки меню.",
        ["OffsetXHelp"] = "Перетащите по горизонтали или введите значение.",
        ["OffsetYHelp"] = "Перетащите по вертикали или введите значение.",
        ["UiScaleHelp"] = "Масштабирует оверлей, не меняя Codex.",
        ["AnimationsHelp"] = "Включает короткие анимации наведения и уведомлений.",
        ["StartWithWindowsHelp"] = "Регистрирует опубликованный exe для входа в Windows.",
        ["ShowAutomaticallyHelp"] = "Управляет автоматическим показом, когда доступно окно Codex.",
        ["LaunchOnStartHelp"] = "Запускает Codex при старте этого приложения.",
        ["LaunchAfterSwitchHelp"] = "Открывает Codex после успешного переключения аккаунта.",
        ["LanguageHelp"] = "Системный режим следует языку интерфейса Windows.",
        ["GracefulTimeoutHelp"] = "Сколько секунд ждать перед запасным принудительным закрытием.",
        ["ForceCloseFallbackHelp"] = "Позволяет завершить переключение, если Codex не закрылся штатно.",
        ["ConfirmForceCloseHelp"] = "Спрашивает подтверждение перед закрытием Codex и сменой активного аккаунта.",
        ["HotkeyHelp"] = "Нажмите поле, затем сочетание клавиш. Escape отменяет, Backspace очищает.",
        ["UseModifier"] = "Используйте хотя бы один модификатор.",
        ["InvalidNumber"] = "Некорректное число.",
        ["CouldNotSaveSettings"] = "Не удалось сохранить настройки.",
        ["ExportSettings"] = "Экспорт настроек",
        ["ImportSettings"] = "Импорт настроек",
        ["ProfileHotkey"] = "Профиль {0}: {1}",
        ["Switching"] = "Переключение...",
        ["AfterMenu"] = "После меню",
        ["TopCenter"] = "Сверху по центру",
        ["TopRight"] = "Сверху справа",
        ["TopLeft"] = "Сверху слева",
        ["Custom"] = "Своя позиция",
        ["Auto"] = "Авто",
        ["Compact"] = "Компактный",
        ["Expanded"] = "Развернутый",

        // Status and limits localization
        ["StatusAndLimits"] = "Статус и лимиты",
        ["ShowAutomaticLimitIndicators"] = "Автоматические индикаторы лимитов",
        ["ShowAutomaticLimitIndicatorsHelp"] = "Проверяет доступные лимиты Codex и показывает небольшой эмодзи рядом с каждым профилем.",
        ["ShowIndicatorsInOverlay"] = "Показывать индикаторы в оверлее",
        ["ShowIndicatorsInOverlayHelp"] = "Отображает индикаторы лимита на кнопках профилей в оверлее и в компактном списке.",
        ["ShowManualEmoji"] = "Показывать ручной эмодзи профиля в оверлее",
        ["ShowManualEmojiHelp"] = "По умолчанию выключено. Автоматический индикатор имеет приоритет, если доступны оба.",
        ["GreenThreshold"] = "Порог зелёного (%)",
        ["GreenThresholdHelp"] = "Зелёный показывается при этом проценте или выше.",
        ["YellowThreshold"] = "Порог жёлтого (%)",
        ["YellowThresholdHelp"] = "Жёлтый начинается с этого процента; меньшие значения показываются красным.",
        ["StaleDataThreshold"] = "Порог устаревших данных (минуты)",
        ["StaleDataThresholdHelp"] = "Минут до пометки данных как устаревших.",
        ["LowWarningThreshold"] = "Порог низкого предупреждения (%)",
        ["LowWarningThresholdHelp"] = "Процент для низкого предупреждения о лимите.",
        ["ActiveProfileRefreshInterval"] = "Интервал обновления активного профиля (минуты)",
        ["ActiveProfileRefreshIntervalHelp"] = "Минут между автоматическим обновлением активного профиля.",
        ["InactiveProfileRefreshInterval"] = "Интервал обновления неактивных профилей (минуты)",
        ["InactiveProfileRefreshIntervalHelp"] = "Минут между автоматическим обновлением неактивных профилей.",
        ["WarnNearlyExhausted"] = "Предупреждать, когда лимит почти закончился",
        ["WarnNearlyExhaustedHelp"] = "Показывает одно локальное уведомление, когда поддерживаемый источник сообщает о низком остатке.",
        ["AutomaticLimitsUnavailable"] = "Автоматические лимиты недоступны",
        ["AutomaticLimitsUnavailableHelp"] = "Для автоматической проверки нужен Codex CLI с поддержкой лимитов app-server. Перед включением фоновых проверок используйте проверку поддержки.",
        ["IndicatorLegend"] = "Обозначения индикаторов",
        ["AutomaticIndicatorExplanation"] = "Индикатор основан на самом строгом доступном окне лимита. Данные могут запаздывать; отсутствие эмодзи означает, что надёжных актуальных данных нет. ⭐ — рекомендация, а не гарантия. Отключение функции убирает все автоматические эмодзи.",
        ["ManualProfileStatus"] = "Ручной статус профиля",
        ["ManualEmoji"] = "Эмодзи",
        ["ManualEmojiHelp"] = "Необязательный эмодзи. Хранится как локальная метаинформация профиля.",
        ["ManualLabel"] = "Короткий текст статуса",
        ["ManualLabelHelp"] = "Необязательно, до 24 символов. Показывается только в настройках.",
        ["ManualNote"] = "Заметка",
        ["ManualNoteHelp"] = "Необязательно, до 120 символов. Никогда не записывается в данные авторизации профиля.",
        ["ManualResetAt"] = "Дата и время сброса",
        ["ManualResetAtHelp"] = "Необязательные локальные дата и время. Внутри сохраняются в UTC.",
        ["CheckThisProfileAutomatically"] = "Проверять этот профиль автоматически",
        ["CheckThisProfileAutomaticallyHelp"] = "Используется только при наличии поддерживаемого источника лимитов.",
        ["InvalidDateTime"] = "Некорректные дата или время.",
        ["RefreshNow"] = "Обновить сейчас",
        ["TestProviderSupport"] = "Проверить поддержку",
        ["LastSuccessfulRefresh"] = "Последнее успешное обновление",
        ["LastSafeError"] = "Последняя безопасная ошибка",
        ["ClearManualStatus"] = "Очистить ручной статус",
        ["ClearCachedUsage"] = "Очистить кэш автоматических данных",
        ["ProviderAvailable"] = "Провайдер автоматических лимитов доступен",
        ["NoReliableUsageData"] = "Нет надёжных актуальных данных о лимитах. Неизвестные значения не показываются как ноль.",
        ["ResetsAt"] = "сброс",
        ["LastUpdated"] = "Последнее обновление",
        ["UsageDataStale"] = "Данные о лимитах устарели",
        ["UsageSource"] = "Источник",
        ["CodexCliVersion"] = "Версия Codex CLI",
        ["LastRefreshAttempt"] = "Последняя попытка обновления",
        ["RefreshError"] = "Ошибка обновления",
        ["UsageWindow"] = "Лимит",

        // Legend
        ["RecommendedProfile"] = "Рекомендуемый профиль",
        ["RecommendedProfileHelp"] = "Сейчас у него больше всего доступного лимита среди проверенных аккаунтов.",
        ["HighCapacity"] = "Лимитов много",
        ["HighCapacityHelp"] = "Можно спокойно продолжать работу.",
        ["MediumCapacity"] = "Средний остаток",
        ["MediumCapacityHelp"] = "Часть лимита уже использована.",
        ["LowCapacity"] = "Лимит почти закончился",
        ["LowCapacityHelp"] = "Лучше выбрать другой профиль или дождаться сброса.",

        // Manual status presets
        ["PresetReady"] = "Свежий",
        ["PresetPartlyUsed"] = "Частично использован",
        ["PresetLow"] = "Мало лимита",
        ["PresetExhausted"] = "Лимит закончился",
        ["PresetResetsSoon"] = "Скоро сброс",
        ["PresetInactive"] = "Не использую",
        ["PresetUnknown"] = "Неизвестно",
    };

    public static LanguagePreference Resolve(LanguagePreference preference, CultureInfo? culture = null)
    {
        if (preference != LanguagePreference.SystemDefault)
        {
            return preference;
        }

        culture ??= CultureInfo.CurrentUICulture;
        return culture.TwoLetterISOLanguageName.Equals("ru", StringComparison.OrdinalIgnoreCase)
            ? LanguagePreference.Russian
            : LanguagePreference.English;
    }

    public static string Text(LanguagePreference preference, string key, params object[] args)
    {
        IReadOnlyDictionary<string, string> dictionary = Resolve(preference) == LanguagePreference.Russian ? Russian : English;
        string value = dictionary.TryGetValue(key, out string? text)
            ? text
            : English.GetValueOrDefault(key, key);
        return args.Length == 0 ? value : string.Format(CultureInfo.CurrentCulture, value, args);
    }

    public static IReadOnlyCollection<string> MissingRussianKeys()
    {
        return English.Keys.Where(key => !Russian.ContainsKey(key)).Order(StringComparer.Ordinal).ToArray();
    }
}
